import {
  JupyterFrontEnd,
  JupyterFrontEndPlugin
} from '@jupyterlab/application';

/**
 * Initialization data for the Jupyterbook_code_caption extension.
 */
const plugin: JupyterFrontEndPlugin<void> = {
  id: 'Jupyterbook_code_caption:caption',
  description: 'Generating captions in jupyter book for figures generated by code',
  autoStart: true,
  activate: (app: JupyterFrontEnd) => {
    console.log('JupyterLab extension Jupyterbook_code_caption is activated!');
  }
};

export default plugin;
